import { useState } from 'react'
import { BookOpen, Check, ExternalLink } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import PageWrapper from '../components/layout/PageWrapper'
import Card from '../components/ui/Card'
import Button from '../components/ui/Button'
import { useSkillGap } from '../context/CareerDataContexts'
import { useNotif } from '../context/NotifContext'
import { ROUTES } from '../utils/constants'
const catalog: Record<string, { name: string; provider: string; duration: string; difficulty: string }> = { React: { name: 'React - The Complete Guide', provider: 'Udemy', duration: '40 hrs', difficulty: 'Intermediate' }, Python: { name: 'Python Bootcamp', provider: 'Coursera', duration: '30 hrs', difficulty: 'Beginner' }, SQL: { name: 'SQL for Data Analysis', provider: 'DataCamp', duration: '20 hrs', difficulty: 'Beginner' }, Docker: { name: 'Docker and Kubernetes', provider: 'Pluralsight', duration: '18 hrs', difficulty: 'Intermediate' }, 'System Design': { name: 'Grokking System Design', provider: 'Educative', duration: '24 hrs', difficulty: 'Advanced' } }
export default function Courses() { const { isAnalyzed, missingSkills } = useSkillGap(); const { addNotif } = useNotif(); const navigate = useNavigate(); const [saved, setSaved] = useState<string[]>([]); const [completed, setCompleted] = useState<string[]>([]); const courseSkills = missingSkills.length ? missingSkills.map(item => item.skill) : []; return <PageWrapper title="Courses" subtitle="Learning recommendations shaped by your gaps"><div className="space-y-6">{!isAnalyzed ? <Card><div className="flex flex-col items-center py-12 text-center"><BookOpen className="text-accent-blue" size={32} /><h2 className="mt-4 text-xl font-bold text-text-primary">Complete skill gap analysis first.</h2><Button className="mt-6" onClick={() => navigate(ROUTES.SKILL_GAP)}>Analyze Skill Gap</Button></div></Card> : <><div><h2 className="text-xl font-bold text-text-primary">Recommended for your gaps</h2><p className="mt-1 text-sm text-text-secondary">Courses are generated from your missing skills.</p></div><div className="grid gap-4 md:grid-cols-2">{courseSkills.map(skill => { const course = catalog[skill] || { name: `${skill} essentials`, provider: 'Skill Twin Academy', duration: '12 hrs', difficulty: 'Intermediate' }; const done = completed.includes(skill); return <Card key={skill}><div className="flex items-start justify-between"><div><span className="badge-warning">{skill}</span><h3 className="mt-3 font-semibold text-text-primary">{course.name}</h3><p className="mt-1 text-sm text-text-secondary">{course.provider} · {course.duration} · {course.difficulty}</p></div>{done && <span className="badge-success">Completed ✓</span>}</div><div className="mt-5 flex flex-wrap gap-2"><Button size="sm" variant="secondary" onClick={() => addNotif({ type: 'info', title: 'Opening course...', message: course.name })}><ExternalLink size={14} />View</Button><Button size="sm" variant="secondary" onClick={() => { setSaved(current => current.includes(skill) ? current : [...current, skill]); addNotif({ type: 'success', title: saved.includes(skill) ? 'Already saved' : `Course saved: ${course.name}`, message: 'Your learning list was updated.' }) }}>{saved.includes(skill) ? <><Check size={14} />Saved ✓</> : 'Save'}</Button><Button size="sm" onClick={() => { setCompleted(current => current.includes(skill) ? current : [...current, skill]); addNotif({ type: 'success', title: `Course completed: ${course.name}`, message: 'Progress updated.' }) }}>{done ? 'Completed ✓' : 'Mark Complete'}</Button></div></Card> })}</div></>}</div></PageWrapper> }
