import React, { createContext, useContext, useEffect, useState } from 'react'
import type { CareerGoal, RoadmapPhase, RoadmapTask, Skill, SkillGapItem, TaskStatus, Proficiency, SkillCategory, Application, KanbanStatus } from '../types'
import { useAuth } from './AuthContext'
import { delay, generateId } from '../utils/formatters'

export interface Project { id: string; name: string; description: string; technologies: string[]; githubUrl: string; liveUrl: string; startDate: string; endDate: string; skillsUsed: string[] }
export interface Certification { id: string; name: string; organization: string; issueDate: string; expiryDate: string; credentialId: string; credentialUrl: string; skillsCovered: string[] }

type Store<T> = { value: T; setValue: React.Dispatch<React.SetStateAction<T>> }
const useStored = <T,>(key: string, initial: T): Store<T> => {
  const [value, setValue] = useState<T>(() => { try { const raw = localStorage.getItem(key); return raw ? JSON.parse(raw) as T : initial } catch { return initial } })
  useEffect(() => { localStorage.setItem(key, JSON.stringify(value)) }, [key, value])
  return { value, setValue }
}

interface SkillContextValue { skills: Skill[]; addSkill: (data: Omit<Skill, 'id' | 'createdAt'>) => Promise<void>; updateSkill: (id: string, data: Partial<Skill>) => Promise<void>; deleteSkill: (id: string) => Promise<void> }
const SkillContext = createContext<SkillContextValue | null>(null)
export const SkillProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => { const { user } = useAuth(); const store = useStored<Skill[]>(`skill_twin_skills_${user?.id || 'guest'}`, []); const addSkill = async (data: Omit<Skill, 'id' | 'createdAt'>) => { await delay(250); store.setValue(items => [...items, { ...data, id: generateId(), createdAt: new Date().toISOString() }]) }; const updateSkill = async (id: string, data: Partial<Skill>) => { await delay(250); store.setValue(items => items.map(item => item.id === id ? { ...item, ...data } : item)) }; const deleteSkill = async (id: string) => { await delay(200); store.setValue(items => items.filter(item => item.id !== id)) }; return <SkillContext.Provider value={{ skills: store.value, addSkill, updateSkill, deleteSkill }}>{children}</SkillContext.Provider> }
export const useSkills = () => { const context = useContext(SkillContext); if (!context) throw new Error('useSkills must be used within SkillProvider'); return context }

interface ProjectContextValue { projects: Project[]; addProject: (data: Omit<Project, 'id'>) => Promise<void>; updateProject: (id: string, data: Partial<Project>) => Promise<void>; deleteProject: (id: string) => Promise<void> }
const ProjectContext = createContext<ProjectContextValue | null>(null)
export const ProjectProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => { const { user } = useAuth(); const store = useStored<Project[]>(`skill_twin_projects_${user?.id || 'guest'}`, []); const addProject = async (data: Omit<Project, 'id'>) => { await delay(250); store.setValue(items => [...items, { ...data, id: generateId() }]) }; const updateProject = async (id: string, data: Partial<Project>) => { await delay(250); store.setValue(items => items.map(item => item.id === id ? { ...item, ...data } : item)) }; const deleteProject = async (id: string) => { await delay(200); store.setValue(items => items.filter(item => item.id !== id)) }; return <ProjectContext.Provider value={{ projects: store.value, addProject, updateProject, deleteProject }}>{children}</ProjectContext.Provider> }
export const useProjects = () => { const context = useContext(ProjectContext); if (!context) throw new Error('useProjects must be used within ProjectProvider'); return context }

interface CertContextValue { certs: Certification[]; addCert: (data: Omit<Certification, 'id'>) => Promise<void>; updateCert: (id: string, data: Partial<Certification>) => Promise<void>; deleteCert: (id: string) => Promise<void> }
const CertContext = createContext<CertContextValue | null>(null)
export const CertProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => { const { user } = useAuth(); const store = useStored<Certification[]>(`skill_twin_certs_${user?.id || 'guest'}`, []); const addCert = async (data: Omit<Certification, 'id'>) => { await delay(250); store.setValue(items => [...items, { ...data, id: generateId() }]) }; const updateCert = async (id: string, data: Partial<Certification>) => { await delay(250); store.setValue(items => items.map(item => item.id === id ? { ...item, ...data } : item)) }; const deleteCert = async (id: string) => { await delay(200); store.setValue(items => items.filter(item => item.id !== id)) }; return <CertContext.Provider value={{ certs: store.value, addCert, updateCert, deleteCert }}>{children}</CertContext.Provider> }
export const useCerts = () => { const context = useContext(CertContext); if (!context) throw new Error('useCerts must be used within CertProvider'); return context }

interface GoalContextValue { goal: CareerGoal | null; setGoal: (data: Omit<CareerGoal, 'id' | 'updatedAt'>) => Promise<void>; isGoalSet: boolean }
const GoalContext = createContext<GoalContextValue | null>(null)
export const CareerGoalProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => { const { user } = useAuth(); const store = useStored<CareerGoal | null>(`skill_twin_goal_${user?.id || 'guest'}`, null); const setGoal = async (data: Omit<CareerGoal, 'id' | 'updatedAt'>) => { await delay(300); store.setValue({ ...data, id: store.value?.id || generateId(), updatedAt: new Date().toISOString() }) }; return <GoalContext.Provider value={{ goal: store.value, setGoal, isGoalSet: Boolean(store.value) }}>{children}</GoalContext.Provider> }
export const useCareerGoal = () => { const context = useContext(GoalContext); if (!context) throw new Error('useCareerGoal must be used within CareerGoalProvider'); return context }

const requiredFor = (role: string) => { const normalized = role.toLowerCase(); if (normalized.includes('data')) return ['SQL', 'Python', 'Excel', 'Tableau', 'Statistics', 'Power BI']; if (normalized.includes('full stack')) return ['React', 'Node.js', 'SQL', 'Git', 'REST APIs', 'Docker']; if (normalized.includes('ml') || normalized.includes('machine')) return ['Python', 'TensorFlow', 'SQL', 'Statistics', 'Docker', 'Git']; if (normalized.includes('front')) return ['React', 'TypeScript', 'CSS', 'Git', 'REST APIs', 'Testing']; return ['Communication', 'Problem Solving', 'Git', 'SQL', 'Testing', 'System Design'] }
interface GapContextValue { gaps: SkillGapItem[]; isAnalyzed: boolean; analyzeGap: () => Promise<void>; strongSkills: SkillGapItem[]; weakSkills: SkillGapItem[]; missingSkills: SkillGapItem[] }
const GapContext = createContext<GapContextValue | null>(null)
export const SkillGapProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => { const { user } = useAuth(); const { skills } = useSkills(); const { goal } = useCareerGoal(); const store = useStored<SkillGapItem[]>(`skill_twin_gap_${user?.id || 'guest'}`, []); const analyzeGap = async () => { if (!goal) return; await delay(2000); const required = requiredFor(goal.targetRole); const results: SkillGapItem[] = required.map(skill => { const found = skills.find(item => item.name.toLowerCase() === skill.toLowerCase()); const status: SkillGapItem['status'] = !found ? 'Missing' : found.proficiency === 'Beginner' ? 'Improve' : 'Strong'; const priority: SkillGapItem['priority'] = status === 'Missing' ? 'High' : status === 'Improve' ? 'Medium' : 'Low'; return { skill, currentLevel: found?.proficiency || 'None', requiredLevel: 'Intermediate', status, priority } }); store.setValue(results) }; const strongSkills = store.value.filter(item => item.status === 'Strong'); const weakSkills = store.value.filter(item => item.status === 'Improve'); const missingSkills = store.value.filter(item => item.status === 'Missing'); return <GapContext.Provider value={{ gaps: store.value, isAnalyzed: store.value.length > 0, analyzeGap, strongSkills, weakSkills, missingSkills }}>{children}</GapContext.Provider> }
export const useSkillGap = () => { const context = useContext(GapContext); if (!context) throw new Error('useSkillGap must be used within SkillGapProvider'); return context }

interface RoadmapContextValue { roadmap: RoadmapPhase[]; generateRoadmap: () => Promise<void>; updateTask: (id: string, status: TaskStatus) => void; completionPercent: number }
const RoadmapContext = createContext<RoadmapContextValue | null>(null)
export const RoadmapProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => { const { user } = useAuth(); const { missingSkills } = useSkillGap(); const store = useStored<RoadmapPhase[]>(`skill_twin_roadmap_${user?.id || 'guest'}`, []); const generateRoadmap = async () => { await delay(2000); const skills = missingSkills.length ? missingSkills.map(item => item.skill) : ['Foundations', 'Communication', 'System Design']; const titles = ['Foundation', 'Core Skills', 'Advanced', 'Projects & Portfolio']; const phases = titles.map((title, index) => { const phaseSkills = skills.slice(index, index + 2); const tasks: RoadmapTask[] = (phaseSkills.length ? phaseSkills : [`${title} milestone`]).map((skill, taskIndex) => ({ id: generateId(), skill, goal: `Build practical evidence for ${skill}`, estimatedTime: `${3 + taskIndex} hrs/week`, status: 'Not Started', week: index * 3 + taskIndex + 1 })); return { id: generateId(), title: `Phase ${index + 1}: ${title}`, description: 'A focused step toward your target role.', weeks: index === 0 ? 'Weeks 1–2' : index === 1 ? 'Weeks 3–6' : index === 2 ? 'Weeks 7–10' : 'Weeks 11–12', tasks, progress: 0 } }); store.setValue(phases) }; const updateTask = (id: string, status: TaskStatus) => store.setValue(phases => phases.map(phase => { const tasks = phase.tasks.map(task => task.id === id ? { ...task, status } : task); return { ...phase, tasks, progress: tasks.length ? Math.round(tasks.filter(task => task.status === 'Completed').length / tasks.length * 100) : 0 } })); const total = store.value.flatMap(phase => phase.tasks); const completionPercent = total.length ? Math.round(total.filter(task => task.status === 'Completed').length / total.length * 100) : 0; return <RoadmapContext.Provider value={{ roadmap: store.value, generateRoadmap, updateTask, completionPercent }}>{children}</RoadmapContext.Provider> }
export const useRoadmap = () => { const context = useContext(RoadmapContext); if (!context) throw new Error('useRoadmap must be used within RoadmapProvider'); return context }

interface ApplicationContextValue { applications: Application[]; addApplication: (data: Omit<Application, 'id' | 'createdAt'>) => void; updateApplication: (id: string, data: Partial<Application>) => void; deleteApplication: (id: string) => void }
const ApplicationContext = createContext<ApplicationContextValue | null>(null)
export const ApplicationProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => { const { user } = useAuth(); const store = useStored<Application[]>(`skill_twin_applications_${user?.id || 'guest'}`, []); const addApplication = (data: Omit<Application, 'id' | 'createdAt'>) => store.setValue(items => [...items, { ...data, id: generateId(), createdAt: new Date().toISOString() }]); const updateApplication = (id: string, data: Partial<Application>) => store.setValue(items => items.map(item => item.id === id ? { ...item, ...data } : item)); const deleteApplication = (id: string) => store.setValue(items => items.filter(item => item.id !== id)); return <ApplicationContext.Provider value={{ applications: store.value, addApplication, updateApplication, deleteApplication }}>{children}</ApplicationContext.Provider> }
export const useApplications = () => { const context = useContext(ApplicationContext); if (!context) throw new Error('useApplications must be used within ApplicationProvider'); return context }

export const useCareerData = () => ({ useSkills, useProjects, useCerts, useCareerGoal, useSkillGap, useRoadmap, useApplications })
export type { Proficiency, SkillCategory, KanbanStatus }
